// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyK-1C_d60FgYUOdZG6NswMZwayd67XI',
    appId: '1:934226884083:web:1e68e4e0775bfc2678ce86',
    messagingSenderId: '934226884083',
    projectId: 'flutteris-f79ac',
    authDomain: 'flutteris-f79ac.firebaseapp.com',
    storageBucket: 'flutteris-f79ac.firebasestorage.app',
    measurementId: 'G-JN9FS919PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruV-Xyk7Csq-ryHUr9UxB2BH3wZRaaf8',
    appId: '1:934226884083:android:08f4b31caaca140578ce86',
    messagingSenderId: '934226884083',
    projectId: 'flutteris-f79ac',
    storageBucket: 'flutteris-f79ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Ewjt7P4csZNDUOri7vAwi9TE4IlWCu8',
    appId: '1:934226884083:ios:bb88a19e350ae93e78ce86',
    messagingSenderId: '934226884083',
    projectId: 'flutteris-f79ac',
    storageBucket: 'flutteris-f79ac.firebasestorage.app',
    iosBundleId: 'com.example.projeis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Ewjt7P4csZNDUOri7vAwi9TE4IlWCu8',
    appId: '1:934226884083:ios:bb88a19e350ae93e78ce86',
    messagingSenderId: '934226884083',
    projectId: 'flutteris-f79ac',
    storageBucket: 'flutteris-f79ac.firebasestorage.app',
    iosBundleId: 'com.example.projeis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUyK-1C_d60FgYUOdZG6NswMZwayd67XI',
    appId: '1:934226884083:web:8b23adf7c288368978ce86',
    messagingSenderId: '934226884083',
    projectId: 'flutteris-f79ac',
    authDomain: 'flutteris-f79ac.firebaseapp.com',
    storageBucket: 'flutteris-f79ac.firebasestorage.app',
    measurementId: 'G-KFPSD23V4V',
  );
}
